"""add_payment_instruments_and_normalized_transactions

Revision ID: aa0066a212d9
Revises: 5219918d4037
Create Date: 2026-02-19 13:49:28.618137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0066a212d9'
down_revision: Union[str, None] = '5219918d4037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'P2P_ACCOUNT', name='paymentinstrumenttype'), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=True),
    sa.Column('last_four_digits', sa.String(length=4), nullable=True),
    sa.Column('account_identifier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='paymentinstrumentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parsed_transaction_id', sa.UUID(), nullable=False),
    sa.Column('payment_instrument_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_normalized', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('DINING', 'GROCERIES', 'GAS', 'TRAVEL', 'SHOPPING', 'ENTERTAINMENT', 'UTILITIES', 'HEALTHCARE', 'TRANSPORTATION', 'PERSONAL_CARE', 'HOME', 'EDUCATION', 'TRANSFER', 'PAYMENT', 'OTHER', name='transactioncategory'), nullable=False),
    sa.Column('category_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('category_source', sa.String(length=50), nullable=True),
    sa.Column('reimbursement_status', sa.Enum('NONE', 'EXPECTED', 'PARTIAL', 'COMPLETE', name='reimbursementstatus'), nullable=False),
    sa.Column('reimbursed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parsed_transaction_id'], ['parsed_transactions.id'], ),
    sa.ForeignKeyConstraint(['payment_instrument_id'], ['payment_instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parsed_transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_transactions')
    op.drop_table('payment_instruments')
    # ### end Alembic commands ###
